name: Create dist and docker build

on:
  push:
    branches:
      - main
jobs:
  build-project-generate-docker-image:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install project dependencies
        run: npm i --exact

      - name: Build project
        run: npm run build

      - name: Set Timezone
        run: sudo timedatectl set-timezone America/Sao_Paulo

      - name: Set VERSION and DATE
        id: set-vars
        run: |
          echo "::set-output name=VERSION::$(node -p "require('./package.json').version")"
          echo "::set-output name=DATE::$(date +'%Y-%m-%d-%H-%M')"

      - name: Create GitHub Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.set-vars.outputs.VERSION }}
          release_name: Release v${{ steps.set-vars.outputs.VERSION }}
          draft: false
          prerelease: false

      - name: Build dist zip
        uses: vimtor/action-zip@v1.1
        with:
          files: dist/
          dest: dist_v${{ steps.set-vars.outputs.VERSION }}_${{ steps.set-vars.outputs.DATE }}.zip

      - name: Upload Zip
        run: gh release upload v${{ steps.set-vars.outputs.VERSION }} dist_v${{ steps.set-vars.outputs.VERSION }}_${{ steps.set-vars.outputs.DATE }}.zip

      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./dist
          file: ./dist/Dockerfile
          push: true
          tags: |
            tglimatech/github-restapi-node-docker:${{ steps.set-vars.outputs.VERSION }}
            tglimatech/github-restapi-node-docker:latest
